CREATE TABLE IF NOT EXISTS APPLICATION
(
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    STATUS VARCHAR(50) NOT NULL,
    COURSE_IDEA VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
