CREATE TABLE IF NOT EXISTS ANSWER
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUIZ_ITEM_ID BIGINT NOT NULL,
    ANSWER_TEXT VARCHAR(255) NOT NULL,
    CORRECT_ANSWER BOOL NOT NULL,
    FOREIGN KEY (QUIZ_ITEM_ID) REFERENCES QUIZ_ITEM(ID)
);
