CREATE TABLE IF NOT EXISTS USER_ANSWER
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ANSWER_ID BIGINT NOT NULL,
    USER_ANSWER_TEXT VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (ANSWER_ID) REFERENCES ANSWER(ID)
);
