CREATE TABLE IF NOT EXISTS COMPETENCE_AREA
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, 'Project Management');
INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, 'Product Design');
INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, 'Software Architecture');
INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, 'Quality Assurance');
INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, 'System Operations');
INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, 'Java Technology');
INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, 'Web & mobile');
INSERT IGNORE INTO COMPETENCE_AREA VALUES(null, '.NET Technology');
