CREATE TABLE IF NOT EXISTS RATING
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    NO_OF_STARS INTEGER NOT NULL,
    DESCRIPTION VARCHAR(255),
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(COURSE_ID) REFERENCES COURSE(ID)
);
