CREATE TABLE IF NOT EXISTS USER
(
    ID                 BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FIRST_NAME         VARCHAR(50)           NOT NULL,
    LAST_NAME          VARCHAR(50)           NOT NULL,
    EMAIL              VARCHAR(50) UNIQUE    NOT NULL,
    IMAGE_URL          VARCHAR(255),
    PASSWORD           VARCHAR(255)          NOT NULL,
    JOB_TITLE_ID       BIGINT                NOT NULL,
    COMPETENCE_AREA_ID BIGINT                NOT NULL,
    USER_TYPE_ID       BIGINT                NOT NULL,

    FOREIGN KEY (JOB_TITLE_ID) REFERENCES JOB_TITLE (ID),
    FOREIGN KEY (COMPETENCE_AREA_ID) REFERENCES COMPETENCE_AREA (ID),
    FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPE (ID)
);
