CREATE TABLE IF NOT EXISTS ENROLLMENT
(
    USER_ID     BIGINT NOT NULL,
    PROGRAM_ID  BIGINT NOT NULL,
    CONSTRAINT USER_PROGRAM PRIMARY KEY (USER_ID, PROGRAM_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(ID)
);
