CREATE TABLE IF NOT EXISTS COURSE
(
    ID             BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME           VARCHAR(50) NOT NULL,
    DESCRIPTION    VARCHAR(255),
    TOTAL_DURATION DOUBLE,
    USER_ID        BIGINT       NOT NULL,
    PROGRAM_ID     BIGINT       NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM (ID)
);
